### ISSUE TITLE
non existent setting host_name

### ISSUE THREAD

**Issue by ghost** [ripienaar/mcollective-vagrant#13]
I'm running in an error, when I run `vagrant up`

```
The following settings don't exist: host_name
```

My Vagrant version is 1.2.7, Windows 7, VirtualBox 4.2.16

To fix it, just edit the Vagrantfile and replace **vmconfig.vm.host_name** with **vmconfig.vm.hostname** and you are done :)

So, the delivered Vagrantfile in the repo isn't consistent, **Vagrant.configure("2")** and should be fixed maybe!?

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
