### ISSUE TITLE
Puppet Errors Following instruction in Readme

### ISSUE THREAD

**Issue by mleone896** [ripienaar/mcollective-vagrant#14]
So after cloning the repo modifying some constants in the Vagrantfile

I get these errors on the vagrant up of middleware
Could not evaluate: uninitialized constant Puppet::FileSystem

Is there something im missing/ should i be using a tagged release of this repo for this to work ? 

Thanks in advance for your help !.

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
