### ISSUE TITLE
uninitialized constant Puppet::FileSystem

### ISSUE THREAD

**Issue by robertkras** [ripienaar/mcollective-vagrant#16]
I have a problem with environment setup. My configuration:
Windows 7 64bit 
Vagrant 1.2.7
VirtualBox 4.2.16

When I'm executing vagrant up command I get following error:
Error: Report processor failed: uninitialized constant Puppet::FileSystem

Full execution log below:
Bringing machine 'middleware' up with 'virtualbox' provider...
Bringing machine 'node0' up with 'virtualbox' provider...
DEPRECATION: `config.env_proxy.*` and `VAGRANT_ENV_*_PROXY`
configuration is deprecated and will be removed in v2.0.0.
Please use `config.proxy.*` and `VAGRANT_*_PROXY` instead.

[middleware] Importing base box 'centos_6_3_x86_64'...

[0K[middleware] Matching MAC address for NAT networking...
DEPRECATION: `config.env_proxy.*` and `VAGRANT_ENV_*_PROXY`
configuration is deprecated and will be removed in v2.0.0.
Please use `config.proxy.*` and `VAGRANT_*_PROXY` instead.

[middleware] Setting the name of the VM...
[middleware] Clearing any previously set forwarded ports...
[middleware] Creating shared folders metadata...
[middleware] Clearing any previously set network interfaces...
[middleware] Preparing network interfaces based on configuration...
[middleware] Forwarding ports...
[middleware] -- 22 => 2222 (adapter 1)
[middleware] Running 'pre-boot' VM customizations...
[middleware] Booting VM...
[middleware] Waiting for VM to boot. This can take a few minutes.
[middleware] VM booted and ready for use!
[middleware] Setting hostname...
[middleware] Configuring and enabling network interfaces...
[middleware] Mounting shared folders...
[middleware] -- /vagrant
[middleware] -- /tmp/vagrant-puppet/manifests
[middleware] -- /tmp/vagrant-puppet/modules-0
[middleware] Configuring proxy environment variables...
[middleware] Configuring proxy for Yum...
[middleware] Running provisioner: puppet...
Running Puppet with site.pp...
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: /Stage[main]//Node[default]/Host[puppet]/ensure: created
Notice: /Stage[main]/Repos/Yumrepo[local-vagrant]/descr: descr changed '' to 'Local packages'
Notice: /Stage[main]/Repos/Yumrepo[local-vagrant]/baseurl: baseurl changed '' to 'file:///vagrant/deploy/packages'
Notice: /Stage[main]/Repos/Yumrepo[local-vagrant]/gpgcheck: gpgcheck changed '' to '0'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-devel]/descr: descr changed '' to 'Puppet Labs Devel El 6 - $basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-devel]/baseurl: baseurl changed '' to 'http://yum.puppetlabs.com/el/6/devel/$basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-devel]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-devel]/gpgcheck: gpgcheck changed '' to '0'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-deps]/descr: descr changed '' to 'Puppet Labs Dependencies El 6 - $basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-deps]/baseurl: baseurl changed '' to 'http://yum.puppetlabs.com/el/6/dependencies/$basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-deps]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-deps]/gpgcheck: gpgcheck changed '' to '0'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-products]/descr: descr changed '' to 'Puppet Labs Products El 6 - $basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-products]/baseurl: baseurl changed '' to 'http://yum.puppetlabs.com/el/6/products/$basearch'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-products]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Repos/Yumrepo[puppetlabs-products]/gpgcheck: gpgcheck changed '' to '0'
Notice: /Stage[main]/Repos/Yumrepo[epel]/descr: descr changed '' to 'Extra Packages for Enterprise Linux 6 - $basearch'
Notice: /Stage[main]/Repos/Yumrepo[epel]/mirrorlist: mirrorlist changed '' to 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
Notice: /Stage[main]/Repos/Yumrepo[epel]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Repos/Yumrepo[epel]/gpgcheck: gpgcheck changed '' to '0'
Notice: /Stage[main]/Repos/Yumrepo[epel]/failovermethod: failovermethod changed '' to 'priority'
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-rake]/ensure: created
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-mcollective-test]/ensure: created
Notice: /Stage[main]/Nrpe/Package[nrpe]/ensure: created
Notice: /Stage[main]/Mcollective::Install/Package[mcollective]/ensure: created
Notice: /Stage[main]/Puppet::Master::Install/Package[puppet-server]/ensure: created
Notice: /Stage[main]/Nrpe/Package[nagios-plugins-all]/ensure: created
Notice: /Stage[main]/Nrpe/File[nrpe_config]/content: content changed '{md5}8900b72b7be7dbaf032516868e022a61' to '{md5}2a65de48d165f7eeff4279af35dbf076'
Error: /Stage[main]/Puppet::Master::Config/File[/etc/puppet/autosign.conf]: Could not evaluate: uninitialized constant Puppet::FileSystem Could not retrieve file metadata for puppet:///modules/puppet/autosign.conf: uninitialized constant Puppet::FileSystem
Notice: /Stage[main]/Redis/File[/etc/logrotate.d/redis]/ensure: defined content as '{md5}7b5aef50c388783e67cb48f50ec270f4'
Notice: /Stage[main]/Redis/Package[redis]/ensure: created
Notice: /Stage[main]/Redis/File[/etc/redis.conf]/content: content changed '{md5}1b59697dc32ec93399fb1828553e5f97' to '{md5}33ad263435520c5d2b470a6c41d3a526'
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-rspec]/ensure: created
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-redis]/ensure: created
Notice: /Stage[main]/Mcollective::Install/Package[mcollective-client]/ensure: created
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-formatr]/ensure: created
Error: /Stage[main]/Puppet::Master::Config/File[/etc/puppet/manifests/site.pp]: Could not evaluate: uninitialized constant Puppet::FileSystem Could not retrieve file metadata for puppet:///modules/puppet/site.pp: uninitialized constant Puppet::FileSystem
Notice: /Stage[main]/Puppet::Master::Service/Service[puppetmaster]: Dependency File[/etc/puppet/autosign.conf] has failures: true
Notice: /Stage[main]/Puppet::Master::Service/Service[puppetmaster]: Dependency File[/etc/puppet/manifests/site.pp] has failures: true
Warning: /Stage[main]/Puppet::Master::Service/Service[puppetmaster]: Skipping because of failed dependencies
Notice: /Stage[main]/Mcollective::Install/Package[gnuplot]/ensure: created
Notice: /Stage[main]/Redis/File[/var/lib/redis/]/group: group changed 'root' to 'redis'
Notice: /Stage[main]/Redis/Service[redis]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Redis/Service[redis]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Mcollective::Install/Package[rubygem-mocha]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Puppet/Mcollective::Plugin[puppet]/Package[mcollective-puppet-common]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Puppet/Mcollective::Plugin[puppet]/Mcollective::Plugin_config[puppet]/File[/etc/mcollective/plugin.d/puppet.cfg]/ensure: defined content as '{md5}8cd038d8af8c4813d8af7c86089ee9ab'
Error: /Stage[main]/Mcollective::Config/File[/etc/mcollective/inventory.mc]: Could not evaluate: uninitialized constant Puppet::FileSystem Could not retrieve file metadata for puppet:///modules/mcollective/inventory.mc: uninitialized constant Puppet::FileSystem
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/client.cfg]/content: content changed '{md5}ef2a5103d23d7acedb5c284729ac3a86' to '{md5}fe9bf0f64bd8885cf990516c4df2d07b'
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/client.cfg]/mode: mode changed '0644' to '0444'
Error: /Stage[main]/Mcollective::Config/File[/usr/libexec/mcollective/mcollective]: Failed to generate additional resources using 'eval_generate: uninitialized constant Puppet::FileSystem
Error: /Stage[main]/Mcollective::Config/File[/usr/libexec/mcollective/mcollective]: Could not evaluate: uninitialized constant Puppet::FileSystem Could not retrieve file metadata for puppet:///modules/mcollective/lib: uninitialized constant Puppet::FileSystem
Notice: /Stage[main]/Mcollective::Agent::Urltest/Mcollective::Plugin[urltest]/Package[mcollective-urltest-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Service/Mcollective::Plugin[service]/Package[mcollective-service-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Package/Mcollective::Plugin[package]/Package[mcollective-package-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Nrpe/Mcollective::Plugin[nrpe]/Package[mcollective-nrpe-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Filemgr/Mcollective::Plugin[filemgr]/Package[mcollective-filemgr-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Service/Mcollective::Plugin[service]/Mcollective::Plugin_config[service]/File[/etc/mcollective/plugin.d/service.cfg]/ensure: defined content as '{md5}45b7964c17acb9b4e10cd27075c8a20e'
Notice: /Stage[main]/Mcollective::Agent::Urltest/Mcollective::Plugin[urltest]/Mcollective::Plugin_config[urltest]/File[/etc/mcollective/plugin.d/urltest.cfg]/ensure: defined content as '{md5}0b179861496f1ccff72143a8120d188f'
Notice: /Stage[main]/Mcollective::Agent::Urltest/Mcollective::Plugin[urltest]/Package[mcollective-urltest-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Filemgr/Mcollective::Plugin[filemgr]/Package[mcollective-filemgr-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Process/Mcollective::Plugin[process]/Mcollective::Plugin_config[process]/File[/etc/mcollective/plugin.d/process.cfg]/ensure: defined content as '{md5}19478496b09ffbcd6df80d9b46407fcf'
Notice: /Stage[main]/Mcollective::Agent::Puppet/Mcollective::Plugin[puppet]/Package[mcollective-puppet-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/server.cfg]/content: content changed '{md5}64c560a3fc9cd6eb8db387224b3b3c02' to '{md5}c6d7480180c88f658b553afb95589b72'
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/server.cfg]/mode: mode changed '0644' to '0500'
Notice: /Stage[main]/Mcollective::Agent::Package/Mcollective::Plugin[package]/Package[mcollective-package-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Nrpe/Mcollective::Plugin[nrpe]/Mcollective::Plugin_config[nrpe]/File[/etc/mcollective/plugin.d/nrpe.cfg]/ensure: defined content as '{md5}3bacb1a6681787c04cd59e70aa712b9b'
Notice: /Stage[main]/Mcollective::Agent::Nrpe/Mcollective::Plugin[nrpe]/Package[mcollective-nrpe-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Package/Mcollective::Plugin[package]/Mcollective::Plugin_config[package]/File[/etc/mcollective/plugin.d/package.cfg]/ensure: defined content as '{md5}81068717a4f0a00b470311985e359432'
Notice: /Stage[main]/Mcollective::Agent::Process/Mcollective::Plugin[process]/Package[mcollective-process-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Process/Mcollective::Plugin[process]/Package[mcollective-process-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Puppet/Mcollective::Plugin[puppet]/Package[mcollective-puppet-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Service/Mcollective::Plugin[service]/Package[mcollective-service-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/facts.yaml]/content: content changed '{md5}385b230b5b4b558f86657dbafe1b5a17' to '{md5}b155798c8d970942977b82663922eff4'
Notice: /Stage[main]/Mcollective::Config/File[/etc/mcollective/facts.yaml]/mode: mode changed '0644' to '0444'
Notice: /Stage[main]/Mcollective::Agent::Integration/Mcollective::Plugin[integration]/Package[mcollective-integration-common]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Integration/Mcollective::Plugin[integration]/Package[mcollective-integration-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Nettest/Mcollective::Plugin[nettest]/Package[mcollective-nettest-client]/ensure: created
Notice: /Stage[main]/Mcollective::Agent::Nettest/Mcollective::Plugin[nettest]/Package[mcollective-nettest-agent]/ensure: created
Notice: /Stage[main]/Mcollective::Service/Service[mcollective]: Dependency File[/usr/libexec/mcollective/mcollective] has failures: true
Notice: /Stage[main]/Mcollective::Service/Service[mcollective]: Dependency File[/etc/mcollective/inventory.mc] has failures: true
Warning: /Stage[main]/Mcollective::Service/Service[mcollective]: Skipping because of failed dependencies
Notice: /Stage[main]/Mcollective::Service/Service[mcollective]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Puppet/Package[puppet]/ensure: ensure changed '3.0.2-1.el6' to '0:3.5.1-0.1rc1.el6'
Notice: /Stage[main]/Nagios/Nrpe::Command[check_disks]/File[/etc/nrpe.d/check_disks.cfg]/ensure: created
Notice: /Stage[main]/Nagios/Nrpe::Command[check_swap]/File[/etc/nrpe.d/check_swap.cfg]/ensure: created
Notice: /Stage[main]/Nagios/Nrpe::Command[check_load]/File[/etc/nrpe.d/check_load.cfg]/ensure: created
Notice: /Stage[main]/Nrpe/Service[nrpe_service]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Nrpe/Service[nrpe_service]: Triggered 'refresh' from 4 events
Notice: /Stage[main]/Motd/File[/etc/motd]: Dependency File[/etc/mcollective/inventory.mc] has failures: true
Notice: /Stage[main]/Motd/File[/etc/motd]: Dependency File[/etc/puppet/manifests/site.pp] has failures: true
Notice: /Stage[main]/Motd/File[/etc/motd]: Dependency File[/usr/libexec/mcollective/mcollective] has failures: true
Notice: /Stage[main]/Motd/File[/etc/motd]: Dependency File[/etc/puppet/autosign.conf] has failures: true
Warning: /Stage[main]/Motd/File[/etc/motd]: Skipping because of failed dependencies
Notice: /Stage[main]/Roles::Middleware/Exec[/usr/bin/curl http://srt.ly/mcvagrantcounter]: Dependency File[/etc/mcollective/inventory.mc] has failures: true
Notice: /Stage[main]/Roles::Middleware/Exec[/usr/bin/curl http://srt.ly/mcvagrantcounter]: Dependency File[/etc/puppet/manifests/site.pp] has failures: true
Notice: /Stage[main]/Roles::Middleware/Exec[/usr/bin/curl http://srt.ly/mcvagrantcounter]: Dependency File[/usr/libexec/mcollective/mcollective] has failures: true
Notice: /Stage[main]/Roles::Middleware/Exec[/usr/bin/curl http://srt.ly/mcvagrantcounter]: Dependency File[/etc/puppet/autosign.conf] has failures: true
Warning: /Stage[main]/Roles::Middleware/Exec[/usr/bin/curl http://srt.ly/mcvagrantcounter]: Skipping because of failed dependencies
Notice: /Stage[main]/Roles::Middleware/Service[iptables]: Dependency File[/etc/mcollective/inventory.mc] has failures: true
Notice: /Stage[main]/Roles::Middleware/Service[iptables]: Dependency File[/etc/puppet/manifests/site.pp] has failures: true
Notice: /Stage[main]/Roles::Middleware/Service[iptables]: Dependency File[/usr/libexec/mcollective/mcollective] has failures: true
Notice: /Stage[main]/Roles::Middleware/Service[iptables]: Dependency File[/etc/puppet/autosign.conf] has failures: true
Warning: /Stage[main]/Roles::Middleware/Service[iptables]: Skipping because of failed dependencies
Notice: /Stage[main]//Node[default]/File[/etc/mcollective/classes.txt]: Dependency File[/etc/mcollective/inventory.mc] has failures: true
Notice: /Stage[main]//Node[default]/File[/etc/mcollective/classes.txt]: Dependency File[/etc/puppet/manifests/site.pp] has failures: true
Notice: /Stage[main]//Node[default]/File[/etc/mcollective/classes.txt]: Dependency File[/usr/libexec/mcollective/mcollective] has failures: true
Notice: /Stage[main]//Node[default]/File[/etc/mcollective/classes.txt]: Dependency File[/etc/puppet/autosign.conf] has failures: true
Warning: /Stage[main]//Node[default]/File[/etc/mcollective/classes.txt]: Skipping because of failed dependencies
Notice: Finished catalog run in 390.27 seconds
Error: Report processor failed: uninitialized constant Puppet::FileSystem

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
