### ISSUE TITLE
key pairs fail for nodes

### ISSUE THREAD

**Issue by hesco** [ripienaar/mcollective-vagrant#27]
During `vagrant up`, I was prompted for a password for each node.  

I used a `vagrant suspend` to shut down for the evening after the initial build and then `vagrant up` again in the morning.  I was still being prompted for a password, although a `ps` list shows my `vagrant ssh` as having been run with `-o IdentitiesOnly=yes -i /Users/escoh/.vagrant.d/insecure_private_key`.  I was able (by manually bringing up the last three nodes) to get `vagrant status` to answer 'running' for each node.  But then after shelling to the middleware machine, `mco ping` showed only the redis machine running.  Attempts to shell into the nodes (from the host) prompt for and reject the default 'vagrant' password for the vagrant user, then freeze my shell, ignoring control-C and requiring a `kill` intervention to reclaim the shell.  I was able to replicate this behavior on two of the nodes, before abandoning the effort.  

Feels like a blocking issue, and I am about to abandon this tutorial / demonstration over it.  

-- Hugh

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
