### ISSUE TITLE
mco process list gets no response from client node

### ISSUE THREAD

**Issue by neverreadsemail** [ripienaar/mcollective-vagrant#28]
Hi,
When using the mcollective vagrant demo, It appears that responses from the node from which mco is run trigger some sort of encode/decode error. this happens regardless of which node I run mco from. e.g. if I run on middleware, then I never get a response from middleware. If I ssh to node0 and run there, I never get a response from node0. this is running with the VirtualBox provider on OSX 10.10.5 vagrant 1.7.4, and git commit 6210e1c645dcbb47e5051cd2f69acaf33f819220 of the mcollective-vagrant repo

here's an example of the error I get:

[vagrant@node0 ~]$ mco process list sshd
- [ ==============================>                               ] 2 / 4warn 2015/11/18 00:56:53: message.rb:189:in `decode!' Failed to decode a message from '': syntax error on line 87, col 13:`            : '
  \ [ =============================================>                ] 3 / 4warn 2015/11/18 00:57:03: client.rb:251:in `start_receiver' Could not receive all responses. Expected : 4. Received : 3
  
   node1.example.net
  
     PID      COMMAND            TTY     STATE
     1252     /usr/sbin/sshd     0       S    
  
  middleware.example.net
  
   PID      COMMAND            TTY     STATE
   1246     /usr/sbin/sshd     0       S    
  
  node2.example.net
  
   PID      COMMAND            TTY     STATE
   1230     /usr/sbin/sshd     0       S    

Summary of The Process List:

```
       Matched hosts: 3
   Matched Processes: 3
       Resident Size: 424.000 KB
        Virtual Size: 187.699 MB
```

Finished processing 3 / 4 hosts in 10010.03 ms

No response from:

```
node0.example.net                                                                           
```

[vagrant@node0 ~]$

-Allie

**Comment by ripienaar** [comment]
I suspect this would be down to the old ruby on here having a terrible yaml library, should probably just work against newer ruby

Alas I do not have time to do such a major rework of this :(

**Comment by neverreadsemail** [comment]
fair enough. At least if there's an issue open, hopefully no one else will waste a day trying to figure out if they're doing something wrong.

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
