### ISSUE TITLE
mco nettest fails

### ISSUE THREAD

**Issue by russellvt** [ripienaar/mcollective-vagrant#29]
As-per the current README.md file, performing a "mco nettest" fails on this example with:

`No request sent, we did not discover any nodes.`

Further investigation from the mcollective.log shows:

> INFO -- : mcollectived:64 The Marionette Collective 2.8.4 started logging at info level
> WARN -- : nettest.rb:11:in `activate?' Cannot load Nettest_agent plugin. Nettest_agent plugin requires the net/ping gem and util/nettest_agent class to run.

...and verifying through "mco inventory" would seem to indicate that the nettest plugin / agent is not installed / activated on either the middleware box, or on any of the nodes. I'm assuming this is just a matter of getting the right ruby gem(s) installed in the right place, everywhere (deploy/packages?)

**Comment by ripienaar** [comment]
Yeah sounds right

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
