### ISSUE TITLE
Not compatible with the latest version of Vagrant

### ISSUE THREAD

**Issue by spuder** [ripienaar/mcollective-vagrant#7]
When trying to run vagrant up with Vagrant 4.2, you get the following warnings: 

There were warnings and/or errors while loading your Vagrantfile.
Your Vagrantfile was written for an earlier version of Vagrant,
and while Vagrant does the best it can to remain backwards
compatible, there are some cases where things have changed
significantly enough to warrant a message. These messages are
shown below.

The creation progress then freezes at this step

[middleware] Setting hostname...
![terminal](https://f.cloud.github.com/assets/242382/1091148/48771932-1663-11e3-80ca-d7d33441a890.png)

**Comment by ripienaar** [comment]
please use https://github.com/choria-io/vagrant-demo
